//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;


    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Papers = new HashSet<Paper>();
            this.Participates = new HashSet<Participate>();
            this.LikeDBs = new HashSet<LikeDB>();
            this.CommentDBs = new HashSet<CommentDB>();
        }

        public int Id { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "Must Enter The First Name")]
        public string FName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Must Enter The Last Name")]
        public string LName { get; set; }
        public Nullable<long> Mobile { get; set; }
        [Required(ErrorMessage = "Must Enter Your University")]
        public string University { get; set; }
        public string Department { get; set; }
        [Required(ErrorMessage = "Must Enter Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Must Enter Password")]
        [DisplayName("New Password")]
        [DataType(DataType.Password)]
        public string Passward { get; set; }
        [DisplayName("Re-New Password")]
        [Required(ErrorMessage = "Must Enter Confirm Your Password")]
        [DataType(DataType.Password)]
        [Compare("Passward")]
        public string ConfirmPassward { get; set; }

        [DisplayName("Upload Photo")]

        public string ImagePath { get; set; }

        public string LoginErrorMsg { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper> Papers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participate> Participates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeDB> LikeDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentDB> CommentDBs { get; set; }
    }
}
